name: Do update

on:
  schedule:
    - cron: '21 0 * * fri'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Run
      run: |
        pipenv run python main.py
    - name: Push to data repo
      env:
        SSH_KEY: ${{ secrets.TODO_DATA_KEY }}
      run: |
        eval $(ssh-agent)
        ssh-add <(echo "$SSH_KEY" | base64 -d)
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
        BRANCH_NAME="wiki-data-$(date +"%Y-%m-%d")"
        mkdir upload
        cd upload
        git init
        git remote add upstream https://github.com/Fiskmans/rl_todo_data.git
        git remote add origin git@github.com:Fiskmans/rl_todo_data.git
        git fetch upstream
        git checkout upstream/gh-pages
        git checkout -b "$BRANCH_NAME"
        mkdir -p item npcs
        cp ../methods.json methods.json
        git add methods.json.json
        git -c user.name="RuneLite (todo) Wiki Scraper" -c user.email="mans@zingo.org" commit -m "Update wiki data" || exit 0
        git push -u origin "$BRANCH_NAME"
